In [24]:
import pandas as pd
import scipy.stats
from pandas import np
import matplotlib.pyplot as plt

df = pd.read_csv('fifa_countries_audience.txt')
def fifa_corr(a, b):
    mean_a = np.mean(a)
    mean_b = np.mean(b)
    
    num = [(i-mean_a)* (j-mean_b) for i, j in zip(a, b)]
 
    corr_a_b = np.sum(num)/(len(a)-1)
    return corr_a_b


# dataset = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2], [1, 4, 3]])
def cov_matrix_calculation(data):
    # calculate covariance matrix of the data
    print(data.T)
    cov_matx = np.cov(data.T)
    return cov_matx

dataset = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2], [1, 4, 3]])
print(cov_matrix_calculation(dataset))





# $(X,Y), (X, Z), (Y, Z), (X, X), (Y, Y), and (Z, Z)$
cov_ab = [[fifa_corr(df['population_share'], df['population_share']), fifa_corr(df['population_share'], df['tv_audience_share']), fifa_corr(df['population_share'], df['gdp_weighted_share'])],
        [fifa_corr(df['tv_audience_share'], df['population_share']), fifa_corr(df['tv_audience_share'], df['tv_audience_share']), fifa_corr(df['tv_audience_share'], df['gdp_weighted_share'])], 
        [fifa_corr(df['gdp_weighted_share'], df['population_share']), fifa_corr(df['gdp_weighted_share'], df['tv_audience_share']), fifa_corr(df['gdp_weighted_share'], df['gdp_weighted_share'])]]

for list_cov in cov_ab:
    print(list_cov)
print()
    
# print(np.cov(df['population_share'], df['tv_audience_share']))
# print(np.cov(df['population_share'], df['gdp_weighted_share']))
# print(np.cov(df['tv_audience_share'], df['gdp_weighted_share']))

#   x y z
# x
# y
# z



[[1 1 1 1]
 [1 2 3 4]
 [1 1 2 3]]
[[0.         0.         0.        ]
 [0.         1.66666667 1.16666667]
 [0.         1.16666667 0.91666667]]
[3.842911545880407, 2.078110223201984, 1.2780115734362083]
[2.078110223201984, 2.101150730228713, 1.628527142463489]
[1.2780115734362083, 1.628527142463489, 2.124580876274456]

