In [3]:
import pandas as pd
import scipy.stats
from pandas import np
import matplotlib.pyplot as plt

df = pd.read_csv('fifa_countries_audience.txt')
def fifa_corr(a, b):
    mean_a = np.mean(a)
    mean_b = np.mean(b)
    
    num = [(i-mean_a)* (j-mean_b) for i, j in zip(a, b)]
 
    corr_a_b = np.sum(num)/(len(a)-1)
    return corr_a_b
# $(X,Y), (X, Z), (Y, Z), (X, X), (Y, Y), and (Z, Z)$
cov_ab = [[fifa_corr(df['population_share'], df['tv_audience_share']), fifa_corr(df['population_share'], df['gdp_weighted_share'])],
        [fifa_corr(df['tv_audience_share'], df['gdp_weighted_share']), fifa_corr(df['population_share'], df['population_share'])], 
        [fifa_corr(df['tv_audience_share'], df['tv_audience_share']), fifa_corr(df['gdp_weighted_share'], df['gdp_weighted_share'])]]

for list_cov in cov_ab:
    print(list_cov)
print()
    
print(np.cov(df['population_share'], df['tv_audience_share']))
print(np.cov(df['population_share'], df['gdp_weighted_share']))
print(np.cov(df['tv_audience_share'], df['gdp_weighted_share']))



[2.078110223201984, 1.2780115734362083]
[1.628527142463489, 3.842911545880407]
[2.101150730228713, 2.124580876274456]

[[3.84291155 2.07811022]
 [2.07811022 2.10115073]]
[[3.84291155 1.27801157]
 [1.27801157 2.12458088]]
[[2.10115073 1.62852714]
 [1.62852714 2.12458088]]
